metal:
  children:
    masters:
      hosts:
        nicky-thinkcenter-0: {ansible_host: 192.168.50.150, mac: '00:23:24:95:61:6a', disk: sda, network_interface: eno1}
        nicky-thinkcenter-1: {ansible_host: 192.168.50.151, mac: 'd8:cb:8a:d0:92:ac', disk: sda, network_interface: eno1}
        nicky-thinkcenter-2: {ansible_host: 192.168.50.152, mac: '44:8a:5b:dd:c0:37', disk: sda, network_interface: eno1}
    workers:
      hosts:
        nicky-thinkcenter-3: {ansible_host: 192.168.50.153, mac: 'd8:cb:8a:5f:ae:c0', disk: sda, network_interface: eno1}
